name: Docker Image CI
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 2 5 * *"
env:
  DOCKER_IMAGE_NAME: docker.io/ndscprm/php
jobs:    
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        php: 
          - version: 5.4.45
            checksum: 25bc4723955f4e352935258002af14a14a9810b491a19400d76fcdfa9d04b28f
          - version: 5.6.40
            checksum: 56fb9878d12fdd921f6a0897e919f4e980d930160e154cbde2cc6d9206a27cac
        distro: [bullseye, bookworm]        
    steps:
    - name: Current DateTime
      id: datetime
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYYMMDD-HHmmss"
        
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      uses: docker/build-push-action@v5.3.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: Dockerfile
        # Build arguments
        build-args: |
          PHP_VERSION=${{ matrix.php.version }} 
          DEBIAN_VERSION=${{ matrix.distro }}
          PHP_TAR_HASH=${{ matrix.php.checksum }}
        # Always attempt to pull all referenced images
        pull: true
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.php.version }}-base-${{ matrix.distro }}-${{ steps.datetime.outputs.time }}
          ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.php.version }}-base-${{ matrix.distro }}
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.php.version }}-base-${{ matrix.distro }}-${{ steps.datetime.outputs.time }}
        cache-to: type=inline
        platforms: linux/amd64
        
    - name: Analyze for critical and high CVEs
      id: docker-scout-cves
      # if: ${{ github.event_name != 'pull_request_target' }}
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.php.version }}-base-${{ matrix.distro }}-${{ steps.datetime.outputs.time }}
        sarif-file: sarif.output.json
        summary: true
    
    - name: Upload SARIF result
      id: upload-sarif
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.output.json
